/**
 * Indian Beaches Dataset with live-style INCOIS parameters
 */

export const DEFAULT_BEACH_IMAGE = 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80';

export const INITIAL_BEACHES = [
  {
    id: 'marina-chennai',
    name: 'Marina Beach',
    state: 'Tamil Nadu',
    latitude: 13.0500,
    longitude: 80.2824,
    imageUrl: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=600&q=80',
    description: 'Second longest natural urban beach in the world, flanked by the Bay of Bengal.',
    reading: {
      waveHeightM: 0.9,
      windSpeedKmph: 18,
      swellPeriodSec: 7,
      waterQualityIndex: 62,
      tsunamiAlert: false,
      stormSurgeAlert: false,
      highWaveAlert: false,
      strongCurrentAlert: false,
    },
  },
  {
    id: 'calangute-goa',
    name: 'Calangute Beach',
    state: 'Goa',
    latitude: 15.5440,
    longitude: 73.7554,
    imageUrl: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=600&q=80',
    description: 'Known as the Queen of Beaches in North Goa with vibrant water activities.',
    reading: {
      waveHeightM: 0.4,
      windSpeedKmph: 11,
      swellPeriodSec: 6,
      waterQualityIndex: 85,
      tsunamiAlert: false,
      stormSurgeAlert: false,
      highWaveAlert: false,
      strongCurrentAlert: false,
    },
  },
  {
    id: 'kovalam-kerala',
    name: 'Kovalam Beach',
    state: 'Kerala',
    latitude: 8.4004,
    longitude: 76.9787,
    imageUrl: 'https://images.unsplash.com/photo-151708601594-c5a97913b21c?auto=format&fit=crop&w=600&q=80',
    description: 'Crescent-shaped sandy beaches divided into three parts with a historic lighthouse.',
    reading: {
      waveHeightM: 1.6,
      windSpeedKmph: 33,
      swellPeriodSec: 11,
      waterQualityIndex: 58,
      tsunamiAlert: false,
      stormSurgeAlert: false,
      highWaveAlert: false,
      strongCurrentAlert: false,
    },
  },
  {
    id: 'puri-odisha',
    name: 'Puri Beach',
    state: 'Odisha',
    latitude: 19.7983,
    longitude: 85.8245,
    imageUrl: 'https://images.unsplash.com/photo-1519046904884-53103b34b206?auto=format&fit=crop&w=600&q=80',
    description: 'Sacred pilgrim beach along the Bay of Bengal known for fine sand and annual festivals.',
    reading: {
      waveHeightM: 2.4,
      windSpeedKmph: 40,
      swellPeriodSec: 13,
      waterQualityIndex: 45,
      tsunamiAlert: false,
      stormSurgeAlert: false,
      highWaveAlert: true,
      strongCurrentAlert: false,
    },
  },
  {
    id: 'rk-vizag',
    name: 'RK Beach',
    state: 'Andhra Pradesh',
    latitude: 17.7104,
    longitude: 83.3244,
    imageUrl: 'https://images.unsplash.com/photo-1473116763249-2faaef81ccda?auto=format&fit=crop&w=600&q=80',
    description: 'Ramakrishna Beach on the eastern coast featuring submarine museum and coastal promenade.',
    reading: {
      waveHeightM: 0.6,
      windSpeedKmph: 14,
      swellPeriodSec: 5,
      waterQualityIndex: 74,
      tsunamiAlert: false,
      stormSurgeAlert: false,
      highWaveAlert: false,
      strongCurrentAlert: false,
    },
  },
  {
    id: 'radhanagar-andaman',
    name: 'Radhanagar Beach',
    state: 'Andaman & Nicobar',
    latitude: 11.9840,
    longitude: 92.9515,
    imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80',
    description: 'Consistently ranked among Asia’s best beaches with crystal clear turquoise water.',
    reading: {
      waveHeightM: 0.3,
      windSpeedKmph: 8,
      swellPeriodSec: 5,
      waterQualityIndex: 94,
      tsunamiAlert: false,
      stormSurgeAlert: false,
      highWaveAlert: false,
      strongCurrentAlert: false,
    },
  },
  {
    id: 'varkala-kerala',
    name: 'Varkala Beach',
    state: 'Kerala',
    latitude: 8.7379,
    longitude: 76.7163,
    imageUrl: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=600&q=80',
    description: 'Majestic red sedimentary cliffs towering over the Arabian Sea with natural mineral springs.',
    reading: {
      waveHeightM: 1.1,
      windSpeedKmph: 22,
      swellPeriodSec: 8,
      waterQualityIndex: 78,
      tsunamiAlert: false,
      stormSurgeAlert: false,
      highWaveAlert: false,
      strongCurrentAlert: false,
    },
  },
];
