/**
 * Worldwide Coastal Registry & Beaches Dataset
 * Features domestic Indian coastlines (INCOIS Certified) and iconic international spots across 5 continents
 */

export const DEFAULT_BEACH_IMAGE = 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80';

export const INITIAL_BEACHES = [
  // =========================================================================
  // 🇮🇳 INDIA (INCOIS CERTIFIED OCEANOGRAPHIC CORE)
  // =========================================================================
  {
    id: 'marina-chennai',
    name: 'Marina Beach',
    state: 'Tamil Nadu',
    country: 'India',
    region: 'india',
    latitude: 13.0500,
    longitude: 80.2824,
    source: 'INCOIS Certified',
    imageUrl: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=600&q=80',
    description: 'Second longest natural urban beach in the world, flanked by the Bay of Bengal.',
    reading: {
      waveHeightM: 0.9,
      windSpeedKmph: 18,
      swellPeriodSec: 7,
      waterQualityIndex: 62,
      tsunamiAlert: false,
      stormSurgeAlert: false,
      highWaveAlert: false,
      strongCurrentAlert: false,
    },
  },
  {
    id: 'calangute-goa',
    name: 'Calangute Beach',
    state: 'Goa',
    country: 'India',
    region: 'india',
    latitude: 15.5440,
    longitude: 73.7554,
    source: 'INCOIS Certified',
    imageUrl: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=600&q=80',
    description: 'Known as the Queen of Beaches in North Goa with vibrant water activities.',
    reading: {
      waveHeightM: 0.4,
      windSpeedKmph: 11,
      swellPeriodSec: 6,
      waterQualityIndex: 85,
      tsunamiAlert: false,
      stormSurgeAlert: false,
      highWaveAlert: false,
      strongCurrentAlert: false,
    },
  },
  {
    id: 'kovalam-kerala',
    name: 'Kovalam Beach',
    state: 'Kerala',
    country: 'India',
    region: 'india',
    latitude: 8.4004,
    longitude: 76.9787,
    source: 'INCOIS Certified',
    imageUrl: 'https://images.unsplash.com/photo-151708601594-c5a97913b21c?auto=format&fit=crop&w=600&q=80',
    description: 'Crescent-shaped sandy beaches divided into three parts with a historic lighthouse.',
    reading: {
      waveHeightM: 1.6,
      windSpeedKmph: 33,
      swellPeriodSec: 11,
      waterQualityIndex: 58,
      tsunamiAlert: false,
      stormSurgeAlert: false,
      highWaveAlert: false,
      strongCurrentAlert: false,
    },
  },
  {
    id: 'puri-odisha',
    name: 'Puri Beach',
    state: 'Odisha',
    country: 'India',
    region: 'india',
    latitude: 19.7983,
    longitude: 85.8245,
    source: 'INCOIS Certified',
    imageUrl: 'https://images.unsplash.com/photo-1519046904884-53103b34b206?auto=format&fit=crop&w=600&q=80',
    description: 'Sacred pilgrim beach along the Bay of Bengal known for fine sand and annual festivals.',
    reading: {
      waveHeightM: 2.4,
      windSpeedKmph: 40,
      swellPeriodSec: 13,
      waterQualityIndex: 45,
      tsunamiAlert: false,
      stormSurgeAlert: false,
      highWaveAlert: true,
      strongCurrentAlert: false,
    },
  },
  {
    id: 'rk-vizag',
    name: 'RK Beach',
    state: 'Andhra Pradesh',
    country: 'India',
    region: 'india',
    latitude: 17.7104,
    longitude: 83.3244,
    source: 'INCOIS Certified',
    imageUrl: 'https://images.unsplash.com/photo-1473116763249-2faaef81ccda?auto=format&fit=crop&w=600&q=80',
    description: 'Ramakrishna Beach on the eastern coast featuring submarine museum and coastal promenade.',
    reading: {
      waveHeightM: 0.6,
      windSpeedKmph: 14,
      swellPeriodSec: 5,
      waterQualityIndex: 74,
      tsunamiAlert: false,
      stormSurgeAlert: false,
      highWaveAlert: false,
      strongCurrentAlert: false,
    },
  },
  {
    id: 'radhanagar-andaman',
    name: 'Radhanagar Beach',
    state: 'Andaman & Nicobar',
    country: 'India',
    region: 'india',
    latitude: 11.9840,
    longitude: 92.9515,
    source: 'INCOIS Certified',
    imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80',
    description: 'Consistently ranked among Asia’s best beaches with crystal clear turquoise water.',
    reading: {
      waveHeightM: 0.3,
      windSpeedKmph: 8,
      swellPeriodSec: 5,
      waterQualityIndex: 94,
      tsunamiAlert: false,
      stormSurgeAlert: false,
      highWaveAlert: false,
      strongCurrentAlert: false,
    },
  },
  {
    id: 'varkala-kerala',
    name: 'Varkala Beach',
    state: 'Kerala',
    country: 'India',
    region: 'india',
    latitude: 8.7379,
    longitude: 76.7163,
    source: 'INCOIS Certified',
    imageUrl: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=600&q=80',
    description: 'Majestic red sedimentary cliffs towering over the Arabian Sea with natural mineral springs.',
    reading: {
      waveHeightM: 1.1,
      windSpeedKmph: 22,
      swellPeriodSec: 8,
      waterQualityIndex: 78,
      tsunamiAlert: false,
      stormSurgeAlert: false,
      highWaveAlert: false,
      strongCurrentAlert: false,
    },
  },
  {
    id: 'juhu-mumbai',
    name: 'Juhu Beach',
    state: 'Maharashtra',
    country: 'India',
    region: 'india',
    latitude: 19.0988,
    longitude: 72.8267,
    source: 'INCOIS Certified',
    imageUrl: 'https://images.unsplash.com/photo-1570168007204-dfb528c6958f?auto=format&fit=crop&w=600&q=80',
    description: 'Iconic Arabian Sea shoreline in western Mumbai renowned for vibrant street food and sunsets.',
    reading: {
      waveHeightM: 1.0,
      windSpeedKmph: 19,
      swellPeriodSec: 7,
      waterQualityIndex: 60,
      tsunamiAlert: false,
      stormSurgeAlert: false,
      highWaveAlert: false,
      strongCurrentAlert: false,
    },
  },

  // =========================================================================
  // 🌏 ASIA-PACIFIC
  // =========================================================================
  {
    id: 'kuta-bali',
    name: 'Kuta Beach',
    state: 'Bali',
    country: 'Indonesia',
    region: 'asia-pacific',
    latitude: -8.7185,
    longitude: 115.1686,
    source: 'Global Oceanic Grid',
    imageUrl: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=600&q=80',
    description: 'World-famous sunset surf beach on southern Bali with wide sands and rolling reef breaks.',
    reading: {
      waveHeightM: 1.3,
      windSpeedKmph: 20,
      swellPeriodSec: 9,
      waterQualityIndex: 82,
      tsunamiAlert: false,
      stormSurgeAlert: false,
      highWaveAlert: false,
      strongCurrentAlert: false,
    },
  },
  {
    id: 'surfers-paradise-goldcoast',
    name: 'Surfers Paradise',
    state: 'Queensland',
    country: 'Australia',
    region: 'asia-pacific',
    latitude: -28.0027,
    longitude: 153.4312,
    source: 'Global Oceanic Grid',
    imageUrl: 'https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?auto=format&fit=crop&w=600&q=80',
    description: 'High-energy Golden Coast playground framed by towering skyscrapers and iconic Pacific breakers.',
    reading: {
      waveHeightM: 1.5,
      windSpeedKmph: 24,
      swellPeriodSec: 10,
      waterQualityIndex: 88,
      tsunamiAlert: false,
      stormSurgeAlert: false,
      highWaveAlert: false,
      strongCurrentAlert: false,
    },
  },
  {
    id: 'patong-phuket',
    name: 'Patong Beach',
    state: 'Phuket',
    country: 'Thailand',
    region: 'asia-pacific',
    latitude: 7.8970,
    longitude: 98.2954,
    source: 'Global Oceanic Grid',
    imageUrl: 'https://images.unsplash.com/photo-1589394815804-964ed0be2eb5?auto=format&fit=crop&w=600&q=80',
    description: 'Bustling crescent bay along the Andaman Sea known for watersports, parasailing, and warm tropical waters.',
    reading: {
      waveHeightM: 0.7,
      windSpeedKmph: 14,
      swellPeriodSec: 6,
      waterQualityIndex: 80,
      tsunamiAlert: false,
      stormSurgeAlert: false,
      highWaveAlert: false,
      strongCurrentAlert: false,
    },
  },
  {
    id: 'manza-okinawa',
    name: 'Manza Beach',
    state: 'Okinawa',
    country: 'Japan',
    region: 'asia-pacific',
    latitude: 26.5050,
    longitude: 127.8570,
    source: 'Global Oceanic Grid',
    imageUrl: 'https://images.unsplash.com/photo-1542051841857-5f90071e7989?auto=format&fit=crop&w=600&q=80',
    description: 'Subtropical Ryukyu coastline surrounded by coral reefs, emerald lagoons, and dramatic limestone cliffs.',
    reading: {
      waveHeightM: 0.5,
      windSpeedKmph: 12,
      swellPeriodSec: 6,
      waterQualityIndex: 92,
      tsunamiAlert: false,
      stormSurgeAlert: false,
      highWaveAlert: false,
      strongCurrentAlert: false,
    },
  },

  // =========================================================================
  // 🇪🇺 EUROPE & MEDITERRANEAN
  // =========================================================================
  {
    id: 'nice-cotedazur',
    name: 'Plage de Nice',
    state: 'Côte d\'Azur',
    country: 'France',
    region: 'europe-med',
    latitude: 43.6952,
    longitude: 7.2656,
    source: 'Global Oceanic Grid',
    imageUrl: 'https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=600&q=80',
    description: 'Famous French Riviera pebble beach along the azure waters of the Baie des Anges.',
    reading: {
      waveHeightM: 0.4,
      windSpeedKmph: 10,
      swellPeriodSec: 5,
      waterQualityIndex: 86,
      tsunamiAlert: false,
      stormSurgeAlert: false,
      highWaveAlert: false,
      strongCurrentAlert: false,
    },
  },
  {
    id: 'marinha-algarve',
    name: 'Praia da Marinha',
    state: 'Algarve',
    country: 'Portugal',
    region: 'europe-med',
    latitude: 37.0898,
    longitude: -8.4129,
    source: 'Global Oceanic Grid',
    imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80',
    description: 'Award-winning Atlantic cove flanked by golden limestone sea stacks, natural arches, and clear water.',
    reading: {
      waveHeightM: 1.1,
      windSpeedKmph: 16,
      swellPeriodSec: 8,
      waterQualityIndex: 90,
      tsunamiAlert: false,
      stormSurgeAlert: false,
      highWaveAlert: false,
      strongCurrentAlert: false,
    },
  },
  {
    id: 'positano-amalfi',
    name: 'Spiaggia Grande',
    state: 'Amalfi Coast',
    country: 'Italy',
    region: 'europe-med',
    latitude: 40.6281,
    longitude: 14.4850,
    source: 'Global Oceanic Grid',
    imageUrl: 'https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=600&q=80',
    description: 'Picturesque Mediterranean beach framed by pastel cliffside houses and Tyrrhenian fishing skiffs.',
    reading: {
      waveHeightM: 0.3,
      windSpeedKmph: 9,
      swellPeriodSec: 5,
      waterQualityIndex: 89,
      tsunamiAlert: false,
      stormSurgeAlert: false,
      highWaveAlert: false,
      strongCurrentAlert: false,
    },
  },
  {
    id: 'psarou-mykonos',
    name: 'Psarou Beach',
    state: 'Cyclades',
    country: 'Greece',
    region: 'europe-med',
    latitude: 37.4161,
    longitude: 25.3375,
    source: 'Global Oceanic Grid',
    imageUrl: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=600&q=80',
    description: 'Sheltered Aegean cove with crystal calm waters, white Aegean sands, and luxury yacht moorings.',
    reading: {
      waveHeightM: 0.3,
      windSpeedKmph: 15,
      swellPeriodSec: 4,
      waterQualityIndex: 94,
      tsunamiAlert: false,
      stormSurgeAlert: false,
      highWaveAlert: false,
      strongCurrentAlert: false,
    },
  },

  // =========================================================================
  // 🌎 AMERICAS
  // =========================================================================
  {
    id: 'copacabana-rio',
    name: 'Copacabana Beach',
    state: 'Rio de Janeiro',
    country: 'Brazil',
    region: 'americas',
    latitude: -22.9711,
    longitude: -43.1822,
    source: 'Global Oceanic Grid',
    imageUrl: 'https://images.unsplash.com/photo-1483729558449-99ef09a8c325?auto=format&fit=crop&w=600&q=80',
    description: 'World-renowned 4km Atlantic promenade lined with calçada mosaic tiles, footvolley, and Sugarloaf views.',
    reading: {
      waveHeightM: 1.4,
      windSpeedKmph: 21,
      swellPeriodSec: 9,
      waterQualityIndex: 75,
      tsunamiAlert: false,
      stormSurgeAlert: false,
      highWaveAlert: false,
      strongCurrentAlert: false,
    },
  },
  {
    id: 'waikiki-hawaii',
    name: 'Waikiki Beach',
    state: 'Hawaii',
    country: 'United States',
    region: 'americas',
    latitude: 21.2766,
    longitude: -157.8275,
    source: 'Global Oceanic Grid',
    imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80',
    description: 'Historic Hawaiian surf sanctuary looking out toward Diamond Head crater with warm Pacific rollers.',
    reading: {
      waveHeightM: 0.8,
      windSpeedKmph: 16,
      swellPeriodSec: 8,
      waterQualityIndex: 92,
      tsunamiAlert: false,
      stormSurgeAlert: false,
      highWaveAlert: false,
      strongCurrentAlert: false,
    },
  },
  {
    id: 'santamonica-california',
    name: 'Santa Monica Beach',
    state: 'California',
    country: 'United States',
    region: 'americas',
    latitude: 34.0099,
    longitude: -118.4965,
    source: 'Global Oceanic Grid',
    imageUrl: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=600&q=80',
    description: 'Wide Pacific coastline ending Route 66, featuring its historic solar Ferris wheel pier and surf breaks.',
    reading: {
      waveHeightM: 1.2,
      windSpeedKmph: 17,
      swellPeriodSec: 10,
      waterQualityIndex: 82,
      tsunamiAlert: false,
      stormSurgeAlert: false,
      highWaveAlert: false,
      strongCurrentAlert: false,
    },
  },
  {
    id: 'delfines-cancun',
    name: 'Playa Delfines',
    state: 'Quintana Roo',
    country: 'Mexico',
    region: 'americas',
    latitude: 21.0611,
    longitude: -86.7801,
    source: 'Global Oceanic Grid',
    imageUrl: 'https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?auto=format&fit=crop&w=600&q=80',
    description: 'Unspoiled Caribbean turquoise waters on the southern tip of Cancún known for dolphin sightings.',
    reading: {
      waveHeightM: 0.7,
      windSpeedKmph: 18,
      swellPeriodSec: 6,
      waterQualityIndex: 87,
      tsunamiAlert: false,
      stormSurgeAlert: false,
      highWaveAlert: false,
      strongCurrentAlert: false,
    },
  },

  // =========================================================================
  // 🌍 AFRICA & MIDDLE EAST
  // =========================================================================
  {
    id: 'campsbay-capetown',
    name: 'Camps Bay Beach',
    state: 'Western Cape',
    country: 'South Africa',
    region: 'africa-me',
    latitude: -33.9513,
    longitude: 18.3780,
    source: 'Global Oceanic Grid',
    imageUrl: 'https://images.unsplash.com/photo-1580618672591-eb180b1a973f?auto=format&fit=crop&w=600&q=80',
    description: 'Pristine white sand beach backdropped by the Twelve Apostles mountain peaks and the South Atlantic.',
    reading: {
      waveHeightM: 1.8,
      windSpeedKmph: 28,
      swellPeriodSec: 12,
      waterQualityIndex: 85,
      tsunamiAlert: false,
      stormSurgeAlert: false,
      highWaveAlert: false,
      strongCurrentAlert: true,
    },
  },
  {
    id: 'jumeirah-dubai',
    name: 'Jumeirah Beach',
    state: 'Dubai',
    country: 'United Arab Emirates',
    region: 'africa-me',
    latitude: 25.2048,
    longitude: 55.2708,
    source: 'Global Oceanic Grid',
    imageUrl: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=600&q=80',
    description: 'White sandy shoreline along the Arabian Gulf offering panoramic views of the Burj Al Arab.',
    reading: {
      waveHeightM: 0.3,
      windSpeedKmph: 12,
      swellPeriodSec: 4,
      waterQualityIndex: 88,
      tsunamiAlert: false,
      stormSurgeAlert: false,
      highWaveAlert: false,
      strongCurrentAlert: false,
    },
  },
  {
    id: 'nungwi-zanzibar',
    name: 'Nungwi Beach',
    state: 'Zanzibar',
    country: 'Tanzania',
    region: 'africa-me',
    latitude: -5.7269,
    longitude: 39.2974,
    source: 'Global Oceanic Grid',
    imageUrl: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=600&q=80',
    description: 'Northern tip of Unguja island renowned for coral sand, wooden dhow boat building, and turquoise tides.',
    reading: {
      waveHeightM: 0.5,
      windSpeedKmph: 14,
      swellPeriodSec: 6,
      waterQualityIndex: 93,
      tsunamiAlert: false,
      stormSurgeAlert: false,
      highWaveAlert: false,
      strongCurrentAlert: false,
    },
  },
];
